### PR TITLE
SBML import fixed in bioscrape types

### PR DESCRIPTION
**Pull request by ayush9pandey**
This PR adds a new `import_sbml` function, available as a utility function, in `bioscrape.types`, you can use it to import an SBML file directly using the Model API of bioscrape. Hence, all components of the model (species, parameters, rules, reactions) are stored directly as bioscrape Model API constructs (no more strings!). 

More importantly, 
* `import_sbml` looks into the kinetic law of reactions in SBML model and finds out the ones with `massaction` propensity type so that they can be stored in bioscrape model as such. This will help improve SBML model simulations with bioscrape because earlier all SBML reactions were stored as `general` propensities.
* I have also added support for `RateRule` from SBML models. Earlier, bioscrape only supported `AssignmentRule` types from a SBML. With this, only the `AlgebraicRule` type of SBML is not supported in bioscrape, something that #37 alludes to as well. 

Other minor changes include
* bioscrape.simulator - added/modified warning messages. 
* gitignore - to ignore test files
* bioscrape.types - functions that had nothing to do with Model class but were its members are now moved out to be used as utility functions. (mostly to do with SBML utility functions). 

This PR also addresses issues #18, #39, and #40 .

### CODE REVIEW

**Comment by WilliamIX** [comment]
Did you make sure all of the examples and tests (in both the tests and examples folder) in bioscrape and  lineages still run correctly?

**Comment by ayush9pandey** [comment]
Yes, all examples, tests, and jupyter notebooks are working (except interacting lineages with SBML). I changed the SBML import methods in some of the notebooks to this new one and it works too (changes committed to this PR).

**Comment by ayush9pandey** [comment]
@WilliamIX Whenever you have some time, can you review this PR and merge it if all looks good?

**Comment by WilliamIX** [comment]
Everything seems to work, although we should sit down and talk about the parameter inference notebooks sometime - as stands, the fits are kinda bad - I think when we release this more officially to the world, we should make sure that the example workbooks produce really great fits. Don't think that is an issue with these updates though!

**Pull request merged**
